/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaproject.view;

import java.awt.CardLayout;
import java.awt.event.MouseListener;
import javaproject.controller.HomeController;
import javax.swing.JPanel;

/**
 *
 * @author ACER
 */
public class DashboardView extends javax.swing.JFrame {
    private CardLayout contentCardLayout;
    private int loggedInUserId;

    // Add your panels and buttons (make sure they're initialized in initComponents)
    private UserVehiclePanel userVehiclePanel;

    /**
     * Creates new form DashboardView
     */
    public DashboardView() {
    this(1);  // Default userId = 1 for testing
}
    public DashboardView(int userId) {
    this.loggedInUserId = userId;
    initComponents();

    // ✅ Set layout before showing any panel
    userContentPanel.setLayout(new java.awt.BorderLayout());

    // ✅ Show Home Panel at launch
    showHomePanel();

    // ✅ Show vehicle panel when button is clicked
    userVehicleButton.addActionListener(e -> {
        userContentPanel.removeAll();
        userVehiclePanel = new UserVehiclePanel(); // Reload in case of updates
        userContentPanel.add(userVehiclePanel, java.awt.BorderLayout.CENTER);
        userContentPanel.revalidate();
        userContentPanel.repaint();
    });

    // ✅ Show Home Panel on Home button click
    HomeButton.addActionListener(e -> {
        showHomePanel();
    });



        // Show home panel when HomeButton clicked
        HomeButton.addActionListener(e -> {
            showHomePanel();
        });
    }

    private void showPanel(String name) {
        contentCardLayout.show(userContentPanel, name);
    }

    private void showHomePanel() {
        UserHomePanel homePanel = new UserHomePanel();
        new HomeController(homePanel, loggedInUserId);

        userContentPanel.removeAll();
        userContentPanel.add(homePanel);
        userContentPanel.revalidate();
        userContentPanel.repaint();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userContentPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        HomeButton = new javax.swing.JButton();
        userVehicleButton = new javax.swing.JButton();
        userProfileButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userContentPanel.setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(new java.awt.Color(44, 47, 54));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/Screenshot (166) (2) (1).png"))); // NOI18N

        HomeButton.setBackground(new java.awt.Color(44, 47, 54));
        HomeButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        HomeButton.setForeground(new java.awt.Color(241, 245, 249));
        HomeButton.setText("Home");
        HomeButton.setBorder(null);
        HomeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        userVehicleButton.setBackground(new java.awt.Color(44, 47, 54));
        userVehicleButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userVehicleButton.setForeground(new java.awt.Color(241, 245, 249));
        userVehicleButton.setText("Vehicles");
        userVehicleButton.setBorder(null);
        userVehicleButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        userVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userVehicleButtonActionPerformed(evt);
            }
        });

        userProfileButton.setBackground(new java.awt.Color(44, 47, 54));
        userProfileButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userProfileButton.setForeground(new java.awt.Color(241, 245, 249));
        userProfileButton.setText("User Profile");
        userProfileButton.setBorder(null);
        userProfileButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        LogoutButton.setBackground(new java.awt.Color(44, 47, 54));
        LogoutButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(241, 245, 249));
        LogoutButton.setText("Logout");
        LogoutButton.setBorder(null);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(HomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userVehicleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(userVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(userProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1151, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userVehicleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userVehicleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DashboardView(1).setVisible(true);  // <-- Pass dummy userId = 1 here for testing
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel userContentPanel;
    private javax.swing.JButton userProfileButton;
    private javax.swing.JButton userVehicleButton;
    // End of variables declaration//GEN-END:variables


public javax.swing.JButton getHomeButton(){
    return HomeButton;
}
public javax.swing.JButton getLogoutButton(){
    return LogoutButton;
}
public javax.swing.JButton getPaymentHistoryButton(){
    return userProfileButton;
}
public javax.swing.JButton getVehicleButton(){
    return userVehicleButton;
}
public javax.swing.JButton getUserProfile(){
    return userProfileButton;
}
public void BackButton(MouseListener listener){
    LogoutButton.addMouseListener(listener);
}

public void userProfiles(MouseListener listener){
    userProfileButton.addMouseListener(listener);
}
public JPanel getUserContentPanel() {
    return userContentPanel;
}

}

