/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaproject.view;

import java.awt.event.ActionListener;
import javax.swing.JPasswordField;

/**
 *
 * @author ACER
 */
public class RegistrationView extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationView
     */
    public RegistrationView() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(30, 30, 47));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FirstName = new javax.swing.JLabel();
        FirstNameFiled = new javax.swing.JTextField();
        LastName = new javax.swing.JLabel();
        LastNameFiled = new javax.swing.JTextField();
        Address = new javax.swing.JLabel();
        AddressFiled = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        EmailFiled = new javax.swing.JTextField();
        PhoneNumber = new javax.swing.JLabel();
        PhoneNumberField = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        Password1 = new javax.swing.JLabel();
        Password2 = new javax.swing.JLabel();
        RegisterButton = new javax.swing.JButton();
        RePasswordField = new javax.swing.JPasswordField();
        PasswordField = new javax.swing.JPasswordField();
        ShowButton1 = new javax.swing.JButton();
        ShowButton2 = new javax.swing.JButton();
        SecurityQuestionField = new javax.swing.JComboBox<>();
        SecurityAnswerField = new javax.swing.JTextField();
        BackToLogin = new javax.swing.JButton();
        SecurityAnswer = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(30, 30, 47));

        jPanel1.setBackground(new java.awt.Color(44, 47, 54));

        FirstName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FirstName.setForeground(new java.awt.Color(255, 255, 255));
        FirstName.setText("First Name:");

        FirstNameFiled.setBackground(new java.awt.Color(102, 102, 102));
        FirstNameFiled.setForeground(new java.awt.Color(255, 255, 255));

        LastName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LastName.setForeground(new java.awt.Color(255, 255, 255));
        LastName.setText("Last Name:");

        LastNameFiled.setBackground(new java.awt.Color(102, 102, 102));
        LastNameFiled.setForeground(new java.awt.Color(255, 255, 255));

        Address.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Address.setForeground(new java.awt.Color(255, 255, 255));
        Address.setText("Address:");

        AddressFiled.setBackground(new java.awt.Color(102, 102, 102));
        AddressFiled.setForeground(new java.awt.Color(255, 255, 255));

        Email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("Email:");

        EmailFiled.setBackground(new java.awt.Color(102, 102, 102));
        EmailFiled.setForeground(new java.awt.Color(255, 255, 255));

        PhoneNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        PhoneNumber.setText("Phone Number:");

        PhoneNumberField.setBackground(new java.awt.Color(102, 102, 102));
        PhoneNumberField.setForeground(new java.awt.Color(255, 255, 255));

        Password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password:");

        Password1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Password1.setForeground(new java.awt.Color(255, 255, 255));
        Password1.setText("Re-entred Password");

        Password2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Password2.setForeground(new java.awt.Color(255, 255, 255));
        Password2.setText("Security Question:");

        RegisterButton.setBackground(new java.awt.Color(255, 0, 0));
        RegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButton.setText("Register");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        RePasswordField.setBackground(new java.awt.Color(102, 102, 102));
        RePasswordField.setForeground(new java.awt.Color(255, 255, 255));

        PasswordField.setBackground(new java.awt.Color(102, 102, 102));
        PasswordField.setForeground(new java.awt.Color(255, 255, 255));

        ShowButton1.setBackground(new java.awt.Color(0, 0, 0));
        ShowButton1.setForeground(new java.awt.Color(255, 255, 255));
        ShowButton1.setText("Show");
        ShowButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowButton1ActionPerformed(evt);
            }
        });

        ShowButton2.setBackground(new java.awt.Color(0, 0, 0));
        ShowButton2.setForeground(new java.awt.Color(255, 255, 255));
        ShowButton2.setText("Show");
        ShowButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowButton2ActionPerformed(evt);
            }
        });

        SecurityQuestionField.setBackground(new java.awt.Color(102, 102, 102));
        SecurityQuestionField.setForeground(new java.awt.Color(255, 255, 255));
        SecurityQuestionField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your nickname?", "What is your favorite color?", "What is your favorite food?", "What is your favorite pet?" }));

        SecurityAnswerField.setBackground(new java.awt.Color(102, 102, 102));
        SecurityAnswerField.setForeground(new java.awt.Color(255, 255, 255));

        BackToLogin.setBackground(new java.awt.Color(0, 102, 102));
        BackToLogin.setForeground(new java.awt.Color(255, 255, 255));
        BackToLogin.setText("Back To Login");

        SecurityAnswer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SecurityAnswer.setForeground(new java.awt.Color(255, 255, 255));
        SecurityAnswer.setText("Security Answer:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(LastName)
                                .addComponent(FirstName)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PhoneNumber)
                                    .addComponent(Password1)
                                    .addComponent(Password2)
                                    .addComponent(SecurityAnswer))))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddressFiled)
                            .addComponent(LastNameFiled)
                            .addComponent(FirstNameFiled, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PhoneNumberField)
                            .addComponent(RePasswordField)
                            .addComponent(PasswordField)
                            .addComponent(SecurityQuestionField, 0, 1, Short.MAX_VALUE)
                            .addComponent(SecurityAnswerField)
                            .addComponent(RegisterButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BackToLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(EmailFiled)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowButton1)
                    .addComponent(ShowButton2))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastNameFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password1)
                    .addComponent(RePasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password2)
                    .addComponent(SecurityQuestionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SecurityAnswerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SecurityAnswer))
                .addGap(18, 18, 18)
                .addComponent(RegisterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BackToLogin)
                .addGap(29, 29, 29))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registration Page");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void ShowButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowButton1ActionPerformed
if (PasswordField.getEchoChar() != (char) 0) {
    PasswordField.setEchoChar((char) 0); // Unmask password
    ShowButton1.setText("Hide");
} else {
    PasswordField.setEchoChar('\u2022'); // Mask password again
    ShowButton1.setText("Show");
}        // TODO add your handling code here:
    }//GEN-LAST:event_ShowButton1ActionPerformed

    private void ShowButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowButton2ActionPerformed
if (RePasswordField.getEchoChar() != (char) 0) {
    RePasswordField.setEchoChar((char) 0); // Unmask password
    ShowButton2.setText("Hide");
} else {
    RePasswordField.setEchoChar('\u2022'); // Mask password again
    ShowButton2.setText("Show");
}        // TODO add your handling code here:
    }//GEN-LAST:event_ShowButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JTextField AddressFiled;
    private javax.swing.JButton BackToLogin;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailFiled;
    private javax.swing.JLabel FirstName;
    private javax.swing.JTextField FirstNameFiled;
    private javax.swing.JLabel LastName;
    private javax.swing.JTextField LastNameFiled;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Password1;
    private javax.swing.JLabel Password2;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PhoneNumber;
    private javax.swing.JTextField PhoneNumberField;
    private javax.swing.JPasswordField RePasswordField;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel SecurityAnswer;
    private javax.swing.JTextField SecurityAnswerField;
    private javax.swing.JComboBox<String> SecurityQuestionField;
    private javax.swing.JButton ShowButton1;
    private javax.swing.JButton ShowButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
 public javax.swing.JTextField getFirstNameTextField(){
        return FirstNameFiled;
    }
    public javax.swing.JTextField getLastNameTextField(){
        return LastNameFiled;
    }
    public javax.swing.JTextField getAddressTextField(){
        return AddressFiled;
    }
    public javax.swing.JTextField getEmailTextField(){
        return EmailFiled;
    }
    public javax.swing.JTextField getPhoneNumberTextField(){
        return PhoneNumberField;
    }
     public javax.swing.JPasswordField getPasswordTextField(){
        return (JPasswordField) PasswordField;
    }
     public javax.swing.JPasswordField getRePasswordTextField(){
        return (JPasswordField) RePasswordField;
    }
    public javax.swing.JTextField getSecurityAnswerTextField(){
        return SecurityAnswerField;
    }
     public void RegistrationUser(ActionListener listener){
         RegisterButton.addActionListener(listener);
     }
     public javax.swing.JButton getBackToLogin(){
         return BackToLogin;
     }
}
