/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaproject.view;

import javax.swing.*;
import java.awt.*;
import javaproject.controller.VehicleController;
import javaproject.model.Vehicle;

/**
 * UserVehiclePanel class displaying a list of vehicles in a scrollable view.
 * This panel is used in the user dashboard to show available vehicles.
 */
public class UserVehiclePanel extends javax.swing.JPanel {
    private JPanel vehicleListPanel;  // Panel that holds individual vehicle cards

    /**
     * Creates new form UserVehiclePanel
     */
    public UserVehiclePanel() {
        initComponents();  // Initialize UI components
        setUpVehicleListPanel();
        loadVehicles();
    }

    /**
     * Load all vehicles from the VehicleController and display them as cards.
     */
    private void loadVehicles() {
        VehicleController controller = VehicleController.getInstance();

        // Loop through all vehicles in the controller
        for (Vehicle v : controller.getAllVehicles()) {
            // Create an ImageIcon from the vehicle's image path
            String imagePath = "/" + v.getImagePath();  // Make sure the path is correct
            ImageIcon icon = loadImage(imagePath);

            // Create a new vehicle card with the vehicle's details
            VehicleCardPanel card = new VehicleCardPanel(
                v.getVehicleId(),
                v.getName(),
                String.valueOf(v.getPrice()),
                v.getStatus(),
                icon
            );

            // Add the card to the vehicle list panel
            vehicleListPanel.add(card);
        }

        // Refresh UI
        vehicleListPanel.revalidate();
        vehicleListPanel.repaint();
    }

    /**
     * Load image using the provided path. If the image path is invalid, return a default image.
     *
     * @param imagePath The path to the image
     * @return ImageIcon of the image or default if path is invalid
     */
    private ImageIcon loadImage(String imagePath) {
        try {
            // Attempt to load the image
            return new ImageIcon(getClass().getResource(imagePath));
        } catch (Exception e) {
            // If image is not found, return a default image
            return new ImageIcon(getClass().getResource("/Dashboard/images/default.png"));
        }
    }

    /**
     * Set up the vehicle list panel with BoxLayout for vertical arrangement.
     */
    private void setUpVehicleListPanel() {
        vehicleListPanel = new JPanel();
        vehicleListPanel.setLayout(new BoxLayout(vehicleListPanel, BoxLayout.Y_AXIS));  // Set vertical BoxLayout
        vehicleListPanel.setPreferredSize(new Dimension(400, 800));  // Optional size for the panel

        // Attach this panel to the scrollPane
        scrollPane.setViewportView(vehicleListPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1092, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
