/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vroomvroomproject1.view;

import java.awt.event.ActionListener;

/**
 *
 * @author dell
 */
public class bookingandcancle extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    public bookingandcancle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
<<<<<<< HEAD
        vehicleModelField = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JToggleButton();
        DescriptionArea = new javax.swing.JTextField();
=======
        model = new javax.swing.JTextField();
        day = new javax.swing.JTextField();
        time = new javax.swing.JTextField();
        wheeler = new javax.swing.JTextField();
        sumbit = new javax.swing.JToggleButton();
        jTextField6 = new javax.swing.JTextField();
>>>>>>> cdf0759e7685da24ea6789cfd511697083599de4
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();

        jLabel2.setText("jLabel2");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("      Date ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 110, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Vehicle Type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 100, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 120, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Vehicle Model");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 110, -1));

<<<<<<< HEAD
        vehicleModelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleModelFieldActionPerformed(evt);
            }
        });
        getContentPane().add(vehicleModelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 130, -1));
=======
        model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelActionPerformed(evt);
            }
        });
        getContentPane().add(model, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 130, -1));
>>>>>>> cdf0759e7685da24ea6789cfd511697083599de4

        day.setText("          Day ");
        getContentPane().add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 120, -1));

        time.setText("         Time");
        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 120, -1));

        wheeler.setText("4 Wheeler");
        wheeler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wheelerActionPerformed(evt);
            }
        });
        getContentPane().add(wheeler, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 110, -1));

<<<<<<< HEAD
        SubmitButton.setBackground(new java.awt.Color(0, 102, 102));
        SubmitButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton.setText("SUBMIT");
        getContentPane().add(SubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 120, -1));

        DescriptionArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescriptionAreaActionPerformed(evt);
            }
        });
        getContentPane().add(DescriptionArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 260, 70));
=======
        sumbit.setBackground(new java.awt.Color(0, 102, 102));
        sumbit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sumbit.setForeground(new java.awt.Color(255, 255, 255));
        sumbit.setText("SUBMIT");
        getContentPane().add(sumbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 120, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 260, 70));
>>>>>>> cdf0759e7685da24ea6789cfd511697083599de4

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Description");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 80, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Cancel Booking Vehicle");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 170, 30));
        getContentPane().add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< HEAD
    private void vehicleModelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleModelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleModelFieldActionPerformed
=======
    private void modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelActionPerformed
>>>>>>> cdf0759e7685da24ea6789cfd511697083599de4

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeActionPerformed

    private void wheelerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wheelerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wheelerActionPerformed

    private void DescriptionAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescriptionAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescriptionAreaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookingandcancle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookingandcancle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookingandcancle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookingandcancle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookingandcancle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< HEAD
    private javax.swing.JTextField DescriptionArea;
    private javax.swing.JToggleButton SubmitButton;
=======
    private javax.swing.JTextField day;
>>>>>>> cdf0759e7685da24ea6789cfd511697083599de4
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
<<<<<<< HEAD
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField vehicleModelField;
    // End of variables declaration//GEN-END:variables

public javax.swing.JTextField getDescription(){
    return DescriptionArea;
}
public javax.swing.JTextField getVehicleModel(){
    return vehicleModelField;
}
public javax.swing.JToggleButton getSubmitButton(){
    return SubmitButton;
}
public void Submit(ActionListener listener){
    SubmitButton.addActionListener(listener);
}
=======
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField model;
    private javax.swing.JToggleButton sumbit;
    private javax.swing.JTextField time;
    private javax.swing.JTextField wheeler;
    // End of variables declaration//GEN-END:variables
public javax.swing.JTextField wheeler(){
        return wheeler;
    }
    public javax.swing.JTextField time(){
        return time;
    }
    public javax.swing.JTextField day(){
        return day;
    }
    public javax.swing.JTextField model(){
        return model;
    }
    public void sumbit(ActionListener listener){
         sumbit.addActionListener(listener);
     }
    
>>>>>>> cdf0759e7685da24ea6789cfd511697083599de4
}
