/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vroomproject1.view;

/**
 *
 * @author Dell
 */
public class Filter extends javax.swing.JPanel {

    /**
     * Creates new form Filter
     */
    public Filter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FilterLabel = new javax.swing.JLabel();
        BrandLabel = new javax.swing.JLabel();
        BrandComboBox = new javax.swing.JComboBox<>();
        VechileTypeLabel = new javax.swing.JLabel();
        TypeComboBox = new javax.swing.JComboBox<>();
        RangeLabel = new javax.swing.JLabel();
        RangeTextField = new javax.swing.JTextField();
        DateLabel = new javax.swing.JLabel();
        NextButton = new javax.swing.JButton();
        DateTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));

        FilterLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        FilterLabel.setText("Filter ");

        BrandLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BrandLabel.setText("Brand");

        BrandComboBox.setBackground(new java.awt.Color(102, 102, 102));
        BrandComboBox.setForeground(new java.awt.Color(255, 255, 255));
        BrandComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        BrandComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrandComboBoxActionPerformed(evt);
            }
        });

        VechileTypeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        VechileTypeLabel.setText("Vechile Type");

        TypeComboBox.setBackground(new java.awt.Color(102, 102, 102));
        TypeComboBox.setForeground(new java.awt.Color(255, 255, 255));
        TypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        RangeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RangeLabel.setText("Range");

        RangeTextField.setBackground(new java.awt.Color(102, 102, 102));

        DateLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DateLabel.setText("Date");

        NextButton.setBackground(new java.awt.Color(102, 102, 102));
        NextButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NextButton.setForeground(new java.awt.Color(255, 255, 255));
        NextButton.setText("Next");

        DateTextField.setBackground(new java.awt.Color(102, 102, 102));
        DateTextField.setForeground(new java.awt.Color(255, 255, 255));
        DateTextField.setText("yy/mm/dd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 263, Short.MAX_VALUE)
                .addComponent(NextButton)
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(BrandLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(VechileTypeLabel)
                            .addComponent(BrandComboBox, 0, 131, Short.MAX_VALUE)
                            .addComponent(TypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RangeLabel)
                            .addComponent(DateLabel)
                            .addComponent(RangeTextField)
                            .addComponent(DateTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(FilterLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FilterLabel)
                .addGap(27, 27, 27)
                .addComponent(BrandLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BrandComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VechileTypeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RangeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RangeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(NextButton)
                .addContainerGap(74, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BrandComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrandComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BrandComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BrandComboBox;
    private javax.swing.JLabel BrandLabel;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JTextField DateTextField;
    private javax.swing.JLabel FilterLabel;
    private javax.swing.JButton NextButton;
    private javax.swing.JLabel RangeLabel;
    private javax.swing.JTextField RangeTextField;
    private javax.swing.JComboBox<String> TypeComboBox;
    private javax.swing.JLabel VechileTypeLabel;
    // End of variables declaration//GEN-END:variables
}
