/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vroomproject1.view;

import java.awt.event.ActionListener;


/**
 *
 * @author Dell
 */
public class PaymentView extends javax.swing.JFrame {
    /**
     * Creates new form PaymentView
     */
    public PaymentView(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoPanel = new javax.swing.JPanel();
        PaymentMethodLabel = new javax.swing.JLabel();
        CreditDebitButton = new javax.swing.JButton();
        ESewaButton = new javax.swing.JButton();
        BankButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CardNumberLabel = new javax.swing.JLabel();
        ExpDateLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        CityLabel = new javax.swing.JLabel();
        StateLabel = new javax.swing.JLabel();
        CountryLabel = new javax.swing.JLabel();
        CVCLabel = new javax.swing.JLabel();
        CardNumTxtField = new javax.swing.JTextField();
        ExpDateTxtField = new javax.swing.JTextField();
        CVCTxtField = new javax.swing.JTextField();
        NameTxtField = new javax.swing.JTextField();
        AddressTxtField = new javax.swing.JTextField();
        CityTxtField = new javax.swing.JTextField();
        StateTxtField = new javax.swing.JTextField();
        CountryTxtField = new javax.swing.JTextField();
        PayButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoPanel.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        PaymentMethodLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PaymentMethodLabel.setText("Payment Method");

        CreditDebitButton.setText("Credit or Debit Card");

        ESewaButton.setText("ESewa");

        BankButton.setText("Bank");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Payment Information");

        CardNumberLabel.setText("Card Number");

        ExpDateLabel.setText("Expiry Date");

        NameLabel.setText("Name on Card");

        AddressLabel.setText("Address");

        CityLabel.setText("City");

        StateLabel.setText("State");

        CountryLabel.setText("Country");

        CVCLabel.setText("CVC");

        CardNumTxtField.setText("000-000-000");
        CardNumTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardNumTxtFieldActionPerformed(evt);
            }
        });

        ExpDateTxtField.setText("mm-dd");

        CVCTxtField.setText("3 digits");

        PayButton.setBackground(new java.awt.Color(51, 204, 0));
        PayButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PayButton.setForeground(new java.awt.Color(255, 255, 255));
        PayButton.setText("Pay Now");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CityLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(StateLabel)
                                .addGap(125, 125, 125))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AddressLabel)
                                            .addComponent(CityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(StateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(CreditDebitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(CardNumberLabel)
                                            .addComponent(CardNumTxtField))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(ExpDateLabel)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(CVCLabel))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(ESewaButton)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(BankButton)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ExpDateTxtField)
                                                .addGap(33, 33, 33)
                                                .addComponent(CVCTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PaymentMethodLabel)
                                            .addComponent(jLabel1)
                                            .addComponent(NameLabel)
                                            .addComponent(NameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(21, 21, 21))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AddressTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CountryTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CountryLabel))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(PayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(PaymentMethodLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreditDebitButton)
                    .addComponent(ESewaButton)
                    .addComponent(BankButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CardNumberLabel)
                    .addComponent(ExpDateLabel)
                    .addComponent(CVCLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CardNumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExpDateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CVCTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(NameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(AddressLabel)
                .addGap(3, 3, 3)
                .addComponent(AddressTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityLabel)
                    .addComponent(StateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CountryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CountryTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PayButton)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CardNumTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardNumTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CardNumTxtFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextField AddressTxtField;
    private javax.swing.JButton BankButton;
    private javax.swing.JLabel CVCLabel;
    private javax.swing.JTextField CVCTxtField;
    private javax.swing.JTextField CardNumTxtField;
    private javax.swing.JLabel CardNumberLabel;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JTextField CityTxtField;
    private javax.swing.JLabel CountryLabel;
    private javax.swing.JTextField CountryTxtField;
    private javax.swing.JButton CreditDebitButton;
    private javax.swing.JButton ESewaButton;
    private javax.swing.JLabel ExpDateLabel;
    private javax.swing.JTextField ExpDateTxtField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameTxtField;
    private javax.swing.JButton PayButton;
    private javax.swing.JLabel PaymentMethodLabel;
    private javax.swing.JLabel StateLabel;
    private javax.swing.JTextField StateTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel logoPanel;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getAddressTxtField(){
        return AddressTxtField;
    }
    public javax.swing.JTextField getCVCTxtField(){
        return CVCTxtField ;
    }
    public javax.swing.JTextField getCardNumTxtField(){
        return CardNumTxtField;
    }
    public javax.swing.JTextField getCityTxtField(){
        return CityTxtField;
    }
    public javax.swing.JTextField getCountryTxtField(){
        return CountryTxtField;
    }
    public javax.swing.JTextField getExpDateTxtField(){
        return ExpDateTxtField;
    }
    public javax.swing.JTextField getNameTxtField(){
        return NameTxtField;
    }
    public javax.swing.JTextField getStateTxtField(){
        return StateTxtField;
    }
    public void setPayButtonListener(ActionListener listener) {
        PayButton.addActionListener(listener);
    }
    public javax.swing.JButton getPayButton() {
        return PayButton;
    }
    public javax.swing.JButton getBankButton(){
        return BankButton;
    }
    public javax.swing.JButton getCreditDebitButton(){
        return CreditDebitButton;
    }
    public javax.swing.JButton getESewaButton(){
        return ESewaButton;
    }
}
