/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Dashboard.swing;

/**
 *
 * @author ASUS
 */
public class VehiclePanel extends javax.swing.JPanel {

    /**
     * Creates new form VehiclePanel
     */
    public VehiclePanel() {
        initComponents();
        loadVehicleList(controller.getAllVehicles());

        vehicleTypeCombo.addActionListener(e -> {
            String selectedType = (String) vehicleTypeCombo.getSelectedItem();
            if (selectedType.equals("All")) {
                loadVehicleList(controller.getAllVehicles());
            } else {
                loadVehicleList(controller.filterByType(selectedType));
            }
        });
    }
    private void loadVehicleList(ArrayList<Vehicle> vehicles) {
        vehiclePanel.removeAll();
        for (Vehicle v : vehicles) {
            JPanel card = new JPanel();
            card.setLayout(new BorderLayout());
            card.setBorder(BorderFactory.createTitledBorder(v.getName()));
            
            JLabel imgLabel = new JLabel(new ImageIcon(v.getImagePath()));
            JLabel details = new JLabel("<html>Type: " + v.getType() + "<br/>Price: $" + v.getPricePerDay() + "/day<br/>Status: " + v.getStatus() + "</html>");
            JButton bookButton = new JButton("Book Now");
            bookButton.setEnabled(v.getStatus().equals("Available"));

            card.add(imgLabel, BorderLayout.CENTER);
            card.add(details, BorderLayout.SOUTH);
            card.add(bookButton, BorderLayout.EAST);

            vehiclePanel.add(card);
        }
        vehiclePanel.revalidate();
        vehiclePanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
